DRIVE = 'pymysql'
DIALECT = 'mysql'
USERNAME = 'root'
PASSWORD = 'sjgzhg_AI_123456'
HOST = '120.77.254.39'
PORT = '3306'
DATABASE = 'train'
DB_URI = '{}+{}://{}:{}@{}:{}/{}?charset=utf8'.format(DIALECT,DRIVE,USERNAME,PASSWORD,HOST,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_ECHO = True